networks:
  default:
    name: infra
    external: true
services:
  nginx:
    image: "nginx:${TAG_NGINX}"
    container_name: nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/conf.d:/etc/nginx/conf.d:ro
     - ./nginx/ssl:/etc/nginx/ssl:ro
     - ./nginx/grid:/usr/share/nginx/html/grid
     - ./selenoid/video:/usr/share/nginx/video:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    logging:
     options:
      max-size: "512m"
    ports:
     - "${ZBR_PORT}:80"
    restart: always
